baseURL = "https://blog.aliu.dev"
languageCode = "en-us"
title = "blog.aliu.dev"
theme = "gokarna"


# Hugo global settings.
relativeURLs    = true
canonifyURLs    = true
enableRobotsTXT = true
enableEmoji     = true

[permalinks]
  posts = "/:year/:month/:day/:slug/"

# gokarna settings.

[params]
  avatarURL = "images/head.jpg"
  avatarSize = "size-xl"
  accentColor = "#FF4D4D"
  socialIcons = [
    {name = "github", rel = "me", url = "https://aliu.info/gh"},
    {name = "twitter", rel = "me", url = "https://aliu.info/twitter"},
    {name = "linkedin", rel = "me", url = "https://aliu.info/in"},
    {name = "email", rel = "me", url = "mailto:andy@aliu.dev"}
  ]
  metaKeywords = ["blog", "aliu", "andy liu", "hugo"]
  showPostsOnHomePage = "recent"
  customFooterHTML = '<img style="vertical-align: middle;" src="https://views.aliu.dev?page={{ .Permalink }}&label=Views" />'
  togglePreviousAndNextButtons = "true"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    pre = "<span data-feather='book'></span>"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    pre = "<span data-feather='tag'></span>"
    name = "Tags"
    url = "/tags/"
    weight = 3

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false