baseURL = "https://blog.aliu.dev"
languageCode = "en-us"
title = "Andy Liu's Blog 👋"
theme = 'hugo-bearblog'

# Hugo global settings.
relativeURLs    = true
canonifyURLs    = true
enableRobotsTXT = true
enableEmoji     = true
enableGitInfo   = true

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[author]
  name = "Andy Liu"

[taxonomies]
  tag      = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    name       = "Posts"
    url        = "/posts"

[params]
  description = "Andy's blog"
  images = ["hello.jpeg"]
  title = "Welcome to Andy's Blog"
  hideMadeWithLine = true
  dateFormat = "2006-01-02"
